version: '3'
services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh:
    # ssh in the Container:   docker exec -u erp -it erp bash
    #
    erp:
      image: sdp.registry.abas.sh/abas/test:2017r4n16p29
      container_name: "erp_2017r4n16p02"

      ports:
      - "${SSH_TEST_PORT:-2205}:22"
      - "${MINI_GUI_PORT:-8001}:80"
      - "${EDP_TEST_PORT:-6560}:6550"
      - "${GUI_TEST_PORT:-48592}:48392"
      - "${JAVA_DEBUG_PORT:-8017}:8017"

      environment:
      - ABAS_HOST=127.0.0.1
      - ABAS_GUI_PORT=${GUI_TEST_PORT:-48592}

      # The hostname is very important, especially if you intend to use `docker commit`
      user: s3
      hostname: dockerbau
      command: /data/starteVersion.sh run

    nexus:
      image: sonatype/nexus:oss
      container_name: "nexus"
      ports:
      - "8081:8081"
